### ISSUE TITLE
Read configuration file from Github

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#154]

**Comment by Tommytrg** [comment]
We need a way to add or update a price feed without making changes in the codebase or releasing a new version. To achieve that, we will continue tracking the data feeds in [dataFeedsRouter.json](https://github.com/witnet/data-feeds-explorer/blob/main/packages/api/src/dataFeedsRouter.json.). But, instead of reading it from the machine, we want to fetch the file from where it is hosted: https://github.com/witnet/data-feeds-explorer/blob/main/packages/api/src/dataFeedsRouter.json.
