### ISSUE TITLE
Assess new pricefeeds reorg

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#360]
- Does the current API model fit the requirements?
- Define and open issues to cover the requirements

**Comment by Tommytrg** [comment]
Some new components need data that is not currently available in the Data Feeds Explorer API, but we can add it with some adjustments.

### Last updates component
- Need a list of the last updated feeds.
> We have this information in the database so we can add a new query to the API to be able to retrieve this information.

### Feed list component
- Paginated list of all feeds.
- Paginated list of feeds filtered by network testnet and name.
> To be able to serve this data, we have to split the feedFullName stored in the database into network, mainnet and name fields.
- Feed sources.
> We don't have this information in the database. The easiest way to get it should be by adding it as a constant in the API.
- All networks in which the feed is deployed.
> We need to add this information to the Data Feeds Explorer cache. It can be computed when we get all the price feeds available using https://raw.githubusercontent.com/witnet/data-feeds-explorer/main/packages/api/src/dataFeedsRouter.json.

### Stats component
- Total number of Data Request solved.
> Fetch this data using the block Explorer API.

### Graph component
- Get price feed information of all supported chains in the last 7 or 30 days.
> We could get this information after splitting the feedFullName field.


Additional suggestions for the Data Feeds Explorer:
- Upgrade the dependencies to use nuxt3 and ESM instead of CJS.
- Prerender all price feeds routes to improve SEO and load dynamic content client side https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering.
- Move the web3Middleware to its own service instead of having it alongside with the API.

**Comment by Tommytrg** [comment]
In addition, we should start consuming the new price feed router that allow to query all the price feeds in the network. By doing that, we will reduce the number of calls we make, increasing the performance and saving RPC calls.

We can consume the [supportedFeeds](https://sepolia.etherscan.io/address/0x9999999d139bdBFbF25923ba39F63bBFc7593400#readProxyContract#F31) method.

The new price feed router could also provide the sources of a data request.

**Comment by Tommytrg** [comment]
Issues created from this assessment: #361, #362, #363, #364, #365
